package registry;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * JDBC access.
 * The schema uses portable SQL so it can move to PostgreSQL (ADR-004).
 */
public final class Db {

    private static final String SCHEMA = """
        CREATE TABLE registrar(
            id VARCHAR(16) PRIMARY KEY,
            name VARCHAR(100) NOT NULL,
            pw_hash VARCHAR(200) NOT NULL,
            cert_fp VARCHAR(100) NOT NULL,
            status VARCHAR(12) NOT NULL,
            balance BIGINT NOT NULL,
            credit_limit BIGINT NOT NULL
        );

        CREATE TABLE contact(
            id VARCHAR(32) PRIMARY KEY,
            sponsor VARCHAR(16) NOT NULL REFERENCES registrar(id),
            name VARCHAR(200) NOT NULL,
            org VARCHAR(200),
            email VARCHAR(200) NOT NULL,
            phone VARCHAR(40),
            country VARCHAR(2) NOT NULL,
            created BIGINT NOT NULL
        );

        CREATE TABLE domains(
            name VARCHAR(253) PRIMARY KEY,
            sponsor VARCHAR(16) NOT NULL REFERENCES registrar(id),
            registrant VARCHAR(32) NOT NULL REFERENCES contact(id),
            state VARCHAR(20) NOT NULL,
            created BIGINT NOT NULL,
            expires BIGINT NOT NULL,
            state_since BIGINT NOT NULL,
            authinfo_hash VARCHAR(200) NOT NULL,
            server_hold BOOLEAN NOT NULL
        );

        CREATE TABLE domain_ns(
            domain_name VARCHAR(253) NOT NULL
                REFERENCES domains(name) ON DELETE CASCADE,
            ns VARCHAR(253) NOT NULL,
            PRIMARY KEY(domain_name, ns)
        );

        /* RFC 5910 - DNSSEC EPP */

        CREATE TABLE domain_ds(
            domain_name VARCHAR(253) NOT NULL
                REFERENCES domains(name) ON DELETE CASCADE,
            key_tag INT NOT NULL,
            alg INT NOT NULL,
            digest_type INT NOT NULL,
            digest VARCHAR(128) NOT NULL,
            PRIMARY KEY(domain_name, key_tag, alg, digest_type)
        );

        CREATE INDEX idx_domain_ds_domain
            ON domain_ds(domain_name);

        CREATE TABLE domain_dnskey(
            domain_name VARCHAR(253) NOT NULL
                REFERENCES domains(name) ON DELETE CASCADE,
            flags INT NOT NULL,
            protocol INT NOT NULL,
            alg INT NOT NULL,
            public_key VARCHAR(2048) NOT NULL,
            PRIMARY KEY(domain_name, flags, protocol, alg, public_key)
        );

        CREATE INDEX idx_domain_dnskey_domain
            ON domain_dnskey(domain_name);

        /* RFC 5731 - Domain transfer state */

        CREATE TABLE domain_transfer(
            domain_name VARCHAR(253) PRIMARY KEY
                REFERENCES domains(name) ON DELETE CASCADE,
            requester VARCHAR(16) NOT NULL REFERENCES registrar(id),
            current_sponsor VARCHAR(16) NOT NULL REFERENCES registrar(id),
            requested BIGINT NOT NULL,
            expires BIGINT NOT NULL
        );

        CREATE INDEX idx_domain_transfer_requester
            ON domain_transfer(requester);

        CREATE TABLE ledger(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            registrar VARCHAR(16) NOT NULL REFERENCES registrar(id),
            domain_name VARCHAR(253),
            kind VARCHAR(12) NOT NULL,
            amount BIGINT NOT NULL,
            ts BIGINT NOT NULL
        );

        CREATE TABLE audit(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ts BIGINT NOT NULL,
            actor VARCHAR(64) NOT NULL,
            act VARCHAR(40) NOT NULL,
            obj VARCHAR(253) NOT NULL,
            detail VARCHAR(500) NOT NULL,
            prev_h VARCHAR(64) NOT NULL,
            h VARCHAR(64) NOT NULL
        );

        CREATE TABLE outbox(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            kind VARCHAR(30) NOT NULL,
            domain_name VARCHAR(253) NOT NULL,
            ts BIGINT NOT NULL,
            published BOOLEAN NOT NULL
        );

        /* RFC 5730 - EPP server message queue */

        CREATE TABLE epp_message(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            registrar VARCHAR(16) NOT NULL REFERENCES registrar(id),
            qdate BIGINT NOT NULL,
            message VARCHAR(2000) NOT NULL
        );

        CREATE INDEX idx_epp_message_registrar
            ON epp_message(registrar, id);

        /* RFC 5732 - Host Objects */

        CREATE TABLE hosts(
            name VARCHAR(253) PRIMARY KEY,
            registrar_id VARCHAR(16) NOT NULL
                REFERENCES registrar(id),
            created BIGINT NOT NULL,
            updated BIGINT NOT NULL
        );

        CREATE TABLE host_addresses(
            host_name VARCHAR(253) NOT NULL
                REFERENCES hosts(name) ON DELETE CASCADE,
            address VARCHAR(45) NOT NULL,
            ip_version INT NOT NULL,
            PRIMARY KEY(host_name, address)
        );

        CREATE INDEX idx_host_addresses_host
            ON host_addresses(host_name);

        CREATE INDEX idx_hosts_registrar
            ON hosts(registrar_id);
        """;

    private final String url;

    private Db(String url) {
        this.url = url;

        try (Connection c = open();
             Statement s = c.createStatement()) {

            for (String ddl : SCHEMA.split(";")) {
                if (!ddl.isBlank()) {
                    try {
                        s.execute(ddl);
                    } catch (SQLException e) {
                        // Existing tables are fine when the application restarts.
                        if (!String.valueOf(e.getMessage())
                                .toLowerCase()
                                .contains("already exists")) {
                            throw e;
                        }
                    }
                }
            }

            c.commit();

        } catch (SQLException e) {
            throw new IllegalStateException(e);
        }
    }

    public static Db inMemory() {
        return new Db(
                "jdbc:h2:mem:"
                        + UUID.randomUUID()
                        + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1"
        );
    }

    public static Db file(String path) {
        return new Db(
                "jdbc:h2:file:"
                        + path
                        + ";MODE=PostgreSQL"
        );
    }

    public Connection open() throws SQLException {
        Connection c = DriverManager.getConnection(
                url,
                "sa",
                ""
        );

        c.setAutoCommit(false);
        return c;
    }

    /* ============================================================
       RFC 5732 - HOST OBJECTS
       ============================================================ */

    public synchronized boolean hostExists(String name) {

        try (Connection c = open();
             var ps = c.prepareStatement(
                     "SELECT 1 FROM hosts WHERE name = ?")) {

            ps.setString(1, name);

            try (var rs = ps.executeQuery()) {
                boolean exists = rs.next();
                c.commit();
                return exists;
            }

        } catch (SQLException e) {
            throw new IllegalStateException(
                    "Unable to check host: " + name,
                    e
            );
        }
    }

    public synchronized void createHost(
            String name,
            String registrarId,
            List<String> ipv4,
            List<String> ipv6) {

        if (hostExists(name)) {
            throw new IllegalStateException(
                    "Host already exists: " + name
            );
        }

        long now = System.currentTimeMillis();

        try (Connection c = open();
             var ps = c.prepareStatement("""
                 INSERT INTO hosts
                     (name, registrar_id, created, updated)
                 VALUES (?, ?, ?, ?)
                 """)) {

            ps.setString(1, name);
            ps.setString(2, registrarId);
            ps.setLong(3, now);
            ps.setLong(4, now);

            ps.executeUpdate();

            insertHostAddresses(c, name, ipv4, 4);
            insertHostAddresses(c, name, ipv6, 6);

            c.commit();

        } catch (SQLException e) {
            throw new IllegalStateException(
                    "Unable to create host: " + name,
                    e
            );
        }
    }

    public synchronized Host getHost(String name) {

        try (Connection c = open();
             var ps = c.prepareStatement("""
                 SELECT name, registrar_id
                 FROM hosts
                 WHERE name = ?
                 """)) {

            ps.setString(1, name);

            try (var rs = ps.executeQuery()) {

                if (!rs.next()) {
                    c.commit();
                    return null;
                }

                String hostName = rs.getString("name");
                String registrarId = rs.getString("registrar_id");

                List<String> ipv4 =
                        getHostAddresses(c, hostName, 4);

                List<String> ipv6 =
                        getHostAddresses(c, hostName, 6);

                c.commit();

                return new Host(
                        hostName,
                        registrarId,
                        ipv4,
                        ipv6
                );
            }

        } catch (SQLException e) {
            throw new IllegalStateException(
                    "Unable to load host: " + name,
                    e
            );
        }
    }

    public synchronized void deleteHost(String name) {

        if (!hostExists(name)) {
            throw new IllegalStateException(
                    "Host does not exist: " + name
            );
        }

        try (Connection c = open();
             var ps = c.prepareStatement(
                     "DELETE FROM hosts WHERE name = ?")) {

            ps.setString(1, name);
            ps.executeUpdate();

            c.commit();

        } catch (SQLException e) {
            throw new IllegalStateException(
                    "Unable to delete host: " + name,
                    e
            );
        }
    }

    public synchronized void updateHost(
            String name,
            List<String> ipv4,
            List<String> ipv6) {

        if (!hostExists(name)) {
            throw new IllegalStateException(
                    "Host does not exist: " + name
            );
        }

        long now = System.currentTimeMillis();

        try (Connection c = open()) {

            try (var delete =
                         c.prepareStatement(
                                 "DELETE FROM host_addresses WHERE host_name = ?")) {

                delete.setString(1, name);
                delete.executeUpdate();
            }

            insertHostAddresses(c, name, ipv4, 4);
            insertHostAddresses(c, name, ipv6, 6);

            try (var update =
                         c.prepareStatement("""
                         UPDATE hosts
                         SET updated = ?
                         WHERE name = ?
                         """)) {

                update.setLong(1, now);
                update.setString(2, name);
                update.executeUpdate();
            }

            c.commit();

        } catch (SQLException e) {
            throw new IllegalStateException(
                    "Unable to update host: " + name,
                    e
            );
        }
    }

    private void insertHostAddresses(
            Connection c,
            String hostName,
            List<String> addresses,
            int version) throws SQLException {

        if (addresses == null || addresses.isEmpty()) {
            return;
        }

        try (var ps = c.prepareStatement("""
            INSERT INTO host_addresses
                (host_name, address, ip_version)
            VALUES (?, ?, ?)
            """)) {

            for (String address : addresses) {

                ps.setString(1, hostName);
                ps.setString(2, address);
                ps.setInt(3, version);

                ps.addBatch();
            }

            ps.executeBatch();
        }
    }

    private List<String> getHostAddresses(
            Connection c,
            String hostName,
            int version) throws SQLException {

        List<String> addresses = new ArrayList<>();

        try (var ps = c.prepareStatement("""
            SELECT address
            FROM host_addresses
            WHERE host_name = ?
              AND ip_version = ?
            ORDER BY address
            """)) {

            ps.setString(1, hostName);
            ps.setInt(2, version);

            try (var rs = ps.executeQuery()) {

                while (rs.next()) {
                    addresses.add(
                            rs.getString("address")
                    );
                }
            }
        }

        return addresses;
    }
}