package registry;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.UUID;

/** JDBC access. The schema uses portable SQL so it can move to PostgreSQL (ADR-004). */
public final class Db {
    private static final String SCHEMA = """
        CREATE TABLE registrar(id VARCHAR(16) PRIMARY KEY, name VARCHAR(100) NOT NULL, pw_hash VARCHAR(200) NOT NULL, cert_fp VARCHAR(100) NOT NULL, status VARCHAR(12) NOT NULL, balance BIGINT NOT NULL, credit_limit BIGINT NOT NULL);
        CREATE TABLE contact(id VARCHAR(32) PRIMARY KEY, sponsor VARCHAR(16) NOT NULL REFERENCES registrar(id), name VARCHAR(200) NOT NULL, org VARCHAR(200), email VARCHAR(200) NOT NULL, phone VARCHAR(40), country VARCHAR(2) NOT NULL, created BIGINT NOT NULL);
        CREATE TABLE domains(name VARCHAR(253) PRIMARY KEY, sponsor VARCHAR(16) NOT NULL REFERENCES registrar(id), registrant VARCHAR(32) NOT NULL REFERENCES contact(id), state VARCHAR(20) NOT NULL, created BIGINT NOT NULL, expires BIGINT NOT NULL, state_since BIGINT NOT NULL, authinfo_hash VARCHAR(200) NOT NULL, server_hold BOOLEAN NOT NULL);
        CREATE TABLE domain_ns(domain_name VARCHAR(253) NOT NULL REFERENCES domains(name) ON DELETE CASCADE, ns VARCHAR(253) NOT NULL, PRIMARY KEY(domain_name, ns));
        CREATE TABLE ledger(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, registrar VARCHAR(16) NOT NULL REFERENCES registrar(id), domain_name VARCHAR(253), kind VARCHAR(12) NOT NULL, amount BIGINT NOT NULL, ts BIGINT NOT NULL);
        CREATE TABLE audit(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ts BIGINT NOT NULL, actor VARCHAR(64) NOT NULL, act VARCHAR(40) NOT NULL, obj VARCHAR(253) NOT NULL, detail VARCHAR(500) NOT NULL, prev_h VARCHAR(64) NOT NULL, h VARCHAR(64) NOT NULL);
        CREATE TABLE outbox(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, kind VARCHAR(30) NOT NULL, domain_name VARCHAR(253) NOT NULL, ts BIGINT NOT NULL, published BOOLEAN NOT NULL)
        """;

    private final String url;

    private Db(String url) {
        this.url = url;
        try (Connection c = open(); Statement s = c.createStatement()) {
            for (String ddl : SCHEMA.split(";\\s*\\n")) {
                if (!ddl.isBlank()) s.execute(ddl);
            }
            c.commit();
        } catch (SQLException e) {
            if (!String.valueOf(e.getMessage()).contains("already exists")) throw new IllegalStateException(e);
        }
    }

    public static Db inMemory() {
        return new Db("jdbc:h2:mem:" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
    }

    public static Db file(String path) {
        return new Db("jdbc:h2:file:" + path + ";MODE=PostgreSQL");
    }

    public Connection open() throws SQLException {
        Connection c = DriverManager.getConnection(url, "sa", "");
        c.setAutoCommit(false);
        return c;
    }
}
